[
{
  "name":"Grand Bahama",
  "boundingbox":{"x":0,"y":0,"w":0,"h":0,"style":""},
  "subsections":[
      {"x":0,"y":0,"w":0,"h":0,"style":""},
      {"x":0,"y":0,"w":0,"h":0,"style":""}
    ],
  "style":{"left":"0px","top":"29px","width":"133px","height":"49px"}
},
{
  "name":"Abaco",
  "boundingbox":{"x":0,"y":0,"w":0,"h":0,"style":""},
  "subsections":[
      {"x":0,"y":0,"w":0,"h":0,"style":""},
      {"x":0,"y":0,"w":0,"h":0,"style":""}
    ],
  "style":{"left":"123px","top":"18px","width":"91px","height":"126px"}
},
{
  "name":"Andros",
  "boundingbox":{"x":49,"y":192,"w":105,"h":177,"style":""},
  "subsections":[
      {"x":49,"y":192,"w":90,"h":101,"style":""},
      {"x":49,"y":293,"w":105,"h":76,"style":""}
    ],
  "style":{"left":"49px","top":"192px","width":"105px","height":"177px"}
},
{
  "name":"New Providence",
  "boundingbox":{"x":0,"y":0,"w":0,"h":0,"style":""},
  "subsections":[
      {"x":0,"y":0,"w":0,"h":0,"style":""},
      {"x":0,"y":0,"w":0,"h":0,"style":""}
    ],
  "style":{"left":"140px","top":"208px","width":"58px","height":"28px"}
},
{
  "name":"Eleuthera",
  "boundingbox":{"x":0,"y":0,"w":0,"h":0,"style":""},
  "subsections":[
      {"x":0,"y":0,"w":0,"h":0,"style":""},
      {"x":0,"y":0,"w":0,"h":0,"style":""}
    ],
  "style":{"left":"212px","top":"160px","width":"90px","height":"112px"}
},
{
  "name":"Cat Island",
  "boundingbox":{"x":0,"y":0,"w":0,"h":0,"style":""},
  "subsections":[
      {"x":0,"y":0,"w":0,"h":0,"style":""},
      {"x":0,"y":0,"w":0,"h":0,"style":""}
    ],
  "style":{"left":"322px","top":"249px","width":"63px","height":"78px"}
},
{
  "name":"San Salvador",
  "boundingbox":{"x":0,"y":0,"w":0,"h":0,"style":""},
  "subsections":[
      {"x":0,"y":0,"w":0,"h":0,"style":""},
      {"x":0,"y":0,"w":0,"h":0,"style":""}
    ],
  "style":{"left":"440px","top":"311px","width":"31px","height":"34px"}
},
{
  "name":"Long Island",
  "boundingbox":{"x":0,"y":0,"w":0,"h":0,"style":""},
  "subsections":[
      {"x":0,"y":0,"w":0,"h":0,"style":""},
      {"x":0,"y":0,"w":0,"h":0,"style":""}
    ],
  "style":{"left":"365px","top":"360px","width":"65px","height":"99px"}
},
{
  "name":"Rum Cay",
  "boundingbox":{"x":0,"y":0,"w":0,"h":0,"style":""},
  "subsections":[
      {"x":0,"y":0,"w":0,"h":0},
      {"x":0,"y":0,"w":0,"h":0}
    ],
  "style":{"left":"402px","top":"355px","width":"33px","height":"24px"}
},
{
  "name":"Crooked Island",
  "boundingbox":{"x":0,"y":0,"w":0,"h":0,"style":""},
  "subsections":[
      {"x":0,"y":0,"w":0,"h":0,"style":""},
      {"x":0,"y":0,"w":0,"h":0,"style":""}
    ],
  "style":{"left":"456px","top":"446px","width":"73px","height":"90px"}
},
{
  "name":"Mayaguana",
  "boundingbox":{"x":0,"y":0,"w":0,"h":0,"style":""},
  "subsections":[
      {"x":0,"y":0,"w":0,"h":0,"style":""},
      {"x":0,"y":0,"w":0,"h":0,"style":""}
    ],
  "style":{"left":"578px","top":"487px","width":"63px","height":"35px"}
},
{
  "name":"Inagua",
  "boundingbox":{"x":0,"y":0,"w":0,"h":0,"style":""},
  "subsections":[
      {"x":0,"y":0,"w":0,"h":0,"style":""},
      {"x":0,"y":0,"w":0,"h":0,"style":""}
    ],
  "style":{"left":"526px","top":"587px","width":"97px","height":"79px"
}}
]